#!/usr/bin/env bash
# Regenerates wiki/skills/INDEX.md from the skill files. Run after each wave.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)/wiki/skills"
OUT="$ROOT/INDEX.md"
total=$(find "$ROOT" -name '*.md' ! -name 'INDEX.md' ! -name 'README.md' ! -name 'ROADMAP.md' | wc -l | tr -d ' ')
{
  echo "# Skill Wiki Index"
  echo ""
  echo "**$total verified skills** across $(find "$ROOT" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ') domains. Generated by \`tests/gen_wiki_index.sh\`."
  echo ""
  for d in $(find "$ROOT" -mindepth 1 -maxdepth 1 -type d | sort); do
    dom=$(basename "$d")
    files=$(find "$d" -name '*.md' ! -name 'ROADMAP.md' | sort)
    [ -z "$files" ] && continue
    count=$(echo "$files" | grep -c . || true)
    printf '## %s (%s)\n\n' "$dom" "$count"
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      name=$(basename "$f" .md)
      desc=$(sed -n 's/^description: *//p' "$f" | head -1 | cut -c1-140)
      printf -- '- **[/%s](%s/%s.md)** — %s\n' "$name" "$dom" "$name" "$desc"
    done <<< "$files"
    echo ""
  done
} > "$OUT"
echo "wrote $OUT ($total skills)"
