#!/usr/bin/env bash
# Regenerates wiki/skills/INDEX.md from the skill files. Run after each wave.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)/wiki/skills"
OUT="$ROOT/INDEX.md"
SKIP='! -name INDEX.md ! -name README.md ! -name ROADMAP.md'
total=$(find "$ROOT" -name '*.md' $SKIP | wc -l | tr -d ' ')
domains=$(find "$ROOT" -mindepth 1 -maxdepth 1 -type d | sort)
ndom=$(echo "$domains" | grep -c . || true)
{
  echo "# Skill Wiki Index"
  echo ""
  echo "**$total verified skills** across **$ndom domains**. Generated by \`tests/gen_wiki_index.sh\` — do not hand-edit."
  echo "See [README.md](README.md) for how the library is organized, and each domain's own README (where present) for curated groupings."
  echo ""
  # Table of contents with counts
  echo "| Domain | Skills | About |"
  echo "|---|---|---|"
  for d in $domains; do
    dom=$(basename "$d")
    count=$(find "$d" -name '*.md' $SKIP | wc -l | tr -d ' ')
    [ "$count" = "0" ] && continue
    about=""
    case "$dom" in
      agents) about="Agent engineering: personas, topologies, tools, harnesses, autonomy" ;;
      ai) about="LLM systems: agents, RAG, evals, inference, guardrails" ;;
      architecture) about="System design: boundaries, DDD, ADRs, resilience" ;;
      backend) about="Server-side patterns: APIs, queues, caching, tenancy" ;;
      business) about="Founder operations: metrics, sales, fundraising, support" ;;
      cloud) about="Cloud platforms: AWS/GCP, IaC, Kubernetes, networking, IAM" ;;
      data) about="Data engineering: pipelines, modeling, lakehouse, streaming" ;;
      databases) about="Operating databases: Postgres, Mongo, SQLite, indexing, backups" ;;
      design) about="Product design: design systems, UX research, interaction, motion" ;;
      devtools) about="Developer tooling: git, CLIs, dev environments, AI pairing" ;;
      docs) about="Documentation craft: writing, references, tutorials, RFCs" ;;
      embedded) about="Embedded & IoT: firmware, RTOS, BLE, MQTT, OTA, fleets" ;;
      engineering) about="Engineering process: monorepos, flags, debt, migrations" ;;
      frameworks) about="Framework expertise: React/Next/Vue/Rails/Spring and 25+ more" ;;
      frontend) about="Web platform: performance, CSS, state, PWA, animation" ;;
      gamedev) about="Game development: engines, loops, netcode, balancing + health-game safety" ;;
      growth) about="Growth engineering: experiments, SEO, lifecycle, funnels" ;;
      health) about="Personal health (safety-gated, non-diagnostic — see its README first)" ;;
      languages) about="Language expertise: 39 languages from Python to Zig" ;;
      leadership) about="Engineering leadership: tech leads, hiring, mentoring, reviews" ;;
      mobile) about="Mobile: SwiftUI, Compose, offline sync, releases, push" ;;
      ops) about="Production operations: observability, incidents, CI/CD, GitOps" ;;
      product) about="Product management: discovery, analytics, adoption" ;;
      second-brain) about="Personal knowledge & life ops: PKM, GTD, reviews, journaling" ;;
      security) about="Security engineering: threat modeling, hardening, response" ;;
      testing) about="Test engineering: pyramids, e2e, contracts, flake control" ;;
    esac
    echo "| [$dom](#$dom) | $count | $about |"
  done
  echo ""
  for d in $domains; do
    dom=$(basename "$d")
    files=$(find "$d" -name '*.md' $SKIP | sort)
    [ -z "$files" ] && continue
    count=$(echo "$files" | grep -c . || true)
    printf '## %s (%s)\n\n' "$dom" "$count"
    if [ -f "$d/README.md" ]; then
      printf '_Curated guide: [%s/README.md](%s/README.md)_\n\n' "$dom" "$dom"
    fi
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      name=$(basename "$f" .md)
      desc=$(sed -n 's/^description: *//p' "$f" | head -1 | sed 's/\. .*//' | cut -c1-160)
      printf -- '- **[/%s](%s/%s.md)** — %s.\n' "$name" "$dom" "$name" "$desc"
    done <<< "$files"
    echo ""
  done
} > "$OUT"
echo "wrote $OUT ($total skills, $ndom domains)"
