name: Lint GitHub Actions

on:
  push:
    paths: ['.github/workflows/**']
  pull_request:
    paths: ['.github/workflows/**']

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install actionlint
        run: |
          curl -sL -o /tmp/dl-actionlint.bash https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash
          bash /tmp/dl-actionlint.bash

      - name: Run actionlint
        run: ./actionlint -shellcheck=""
